### ISSUE TITLE
polybar on i3

### ISSUE THREAD

**Issue by drmarwat** [benofbrown/dotfiles#2]
ben,
i am trying out same polybar on my i3 and it loads but from terminal i get some out puts about fonts missing

error: tray: Failed to put tray above 0x0e00002 in the stack (XCB_MATCH (8))
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ���� (U+1f50c)
warn: Dropping unmatched character ��� (U+2588)
warn: Dropping unmatched character ���� (U+1f321)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ���� (U+1f50c)
warn: Dropping unmatched character ��� (U+2588)
warn: Dropping unmatched character ���� (U+1f321)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ���� (U+1f50c)
warn: Dropping unmatched character ��� (U+2588)
warn: Dropping unmatched character ���� (U+1f321)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ���� (U+1f50c)
warn: Dropping unmatched character ��� (U+2588)
warn: Dropping unmatched character ���� (U+1f321)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ��� (U+2581)
warn: Dropping unmatched character ���� (U+1f50c)
warn: Dropping unmatched character ��� (U+2588)
warn: Dropping unmatched character ���� (U+1f321)

which fonts i need to get ?

also what about the position of workstations on polybar? i dont see any window/desktop buttons on polybar on my i3 . what changes do i need to make in config file?

**Comment by benofbrown** [comment]
If you have a look at my `.Xresources` I've listed the fonts there, at least their debian package names. I'm sure your search engine of choice will help you find what you need on your specific distro.

https://github.com/benofbrown/dotfiles/blob/c003ab9407f007870c86811e7191ec88277b0fe0/x11/.Xresources#L72

As for i3, I've never even used it, so I have no idea. I only have i3 config there for polybar because that is what was in the example config in the debian package, which I copied to add my config to.

**Comment by drmarwat** [comment]
Thank you , I have learned a lot from your polybar config file , did set
all the fonts , added few things and removed few and now your my own
modified version of your polybar works amazing .
